language: objective-c
osx_image: xcode8
sudo: false
rvm:
  - 2.3

cache:



env:
  global:
    - WORKSPACE="RxTodoMVP/RxTodoMVP.xcworkspace"
    - SCHEME="RxTodoMVP"
    - IOS_SDK="iphonesimulator10.3"
  matrix:
    - SDK="$IOS_SDK"  DESTINATION="platform=iOS Simulator,name=iPhone 7,OS=10.3"

install:
  - bundle install --deployment
  - bundle exec pod --version
  - bundle exec pod repo update --verbose
  - bundle exec pod install

before_script:
  - set -o pipefail

script:
  - xcodebuild clean build test
    -workspace "$WORKSPACE"
    -scheme "$SCHEME" 
    -sdk "$SDK"
    -destination "$DESTINATION"
    -configuration Debug
    CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO | xcpretty -c
