# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'RxTodoMVP' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for RxTodoMVP
  pod 'RxSwift',    '~> 3.0'
  pod 'RxCocoa',    '~> 3.0'
  pod 'Then',       '~> 2.1'
  pod 'Toaster',    '~> 2.0'
  pod 'SnapKit',    '~> 3.2.0'

  target 'RxTodoMVPTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'RxTodoMVPUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
